name: Build stage

on:
    workflow_dispatch: ~
    workflow_call:
        # Map the workflow outputs to job outputs
        inputs:
            triggering-sha:
                required: true
                type: string

concurrency:
    group: ${{ github.workflow }}-${{ inputs.triggering-sha || github.run_id }}
    cancel-in-progress: true

jobs:
    build:
        name: Build images
        runs-on: ubuntu-22.04
        timeout-minutes: 10
        steps:
            - name: Checkout on SHA-${{ inputs.triggering-sha }}
              uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.triggering-sha }}

            - name: Show CI job info (dump context)
              if: ${{ vars.SHOW_JOB_GHA_CONTEXT == '1'}}
              uses: crazy-max/ghaction-dump-context@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker images
              uses: docker/bake-action@v5
              with:
                pull: true
                load: true
                files: |
                  compose.yaml
                  compose.override.yaml
                set: |
                  php.cache-from=type=gha,scope=php-${{github.ref}}
                  php.cache-from=type=gha,scope=php-refs/heads/main
                  php.cache-to=type=gha,scope=php-${{github.ref}},mode=max
                  pwa.cache-from=type=gha,scope=pwa-${{github.ref}}
                  pwa.cache-from=type=gha,scope=pwa-refs/heads/main
                  pwa.cache-to=type=gha,scope=pwa-${{github.ref}},mode=max

            - name: Start services
              run: docker compose up --wait --no-build

            - name: Check HTTP reachability
              run: curl -v --fail-with-body http://localhost


    lint:
        name: Docker Lint
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout on SHA-${{ inputs.triggering-sha }}
              uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.triggering-sha }}
            
            - name: Lint Dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                recursive: true