name: CD/CI

on: [ push ]

jobs:
  commit-stage-workflow:
    name: Commit Stage
    uses: zerai/esb/.github/workflows/commit-stage.yaml@main
    with:
      triggering-sha: "${{ github.sha }}"

  build-stage-workflow:
    name: Build Stage
    uses: zerai/esb/.github/workflows/build-stage.yaml@main
    secrets: inherit
    with:
      triggering-sha: "${{ github.sha }}"
  
  acceptance-stage-workflow:
    name: Acceptance Stage
    needs:
        - build-stage-workflow
    uses: zerai/esb/.github/workflows/acceptance-stage.yaml@main
    secrets: inherit
    with:
      triggering-sha: "${{ github.sha }}"

